Fix: BadRequest: NetworkAcls is required for this resouce. (#799)
* Fix: BadRequest: NetworkAcls is required for this resouce.

Fixes the error:

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
BadRequest: NetworkAcls is required for this resouce.

* Updating bicep file

---------

Co-authored-by: Pamela Fox <pamela.fox@gmail.com>
Co-authored-by: Pamela Fox <pamelafox@microsoft.com>